/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1d",
        "primary-fixed": "#d7e2ff",
        "on-secondary-fixed": "#081b38",
        "on-primary-container": "#9bbdff",
        "outline-variant": "#c2c6d3",
        secondary: "#4e5f7f",
        "on-secondary-fixed-variant": "#364766",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb694",
        "surface-container-low": "#f2f4f5",
        "surface-container-high": "#e6e8e9",
        primary: "#00346f",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#b6c7ec",
        "on-surface-variant": "#424751",
        "surface-container-highest": "#e1e3e4",
        "on-primary-fixed-variant": "#00458f",
        outline: "#737783",
        "tertiary-container": "#833301",
        "on-primary-fixed": "#001b3f",
        "on-secondary": "#ffffff",
        tertiary: "#5f2200",
        "surface-bright": "#f8fafb",
        "tertiary-fixed": "#ffdbcc",
        "inverse-on-surface": "#eff1f2",
        "inverse-surface": "#2e3132",
        "primary-fixed-dim": "#abc7ff",
        background: "#f8fafb",
        "inverse-primary": "#abc7ff",
        "secondary-container": "#c6d7fd",
        "surface-variant": "#e1e3e4",
        "on-tertiary-container": "#ffa77e",
        "on-tertiary-fixed": "#351000",
        surface: "#f8fafb",
        "on-error": "#ffffff",
        "secondary-fixed": "#d7e2ff",
        error: "#ba1a1a",
        "surface-tint": "#255dad",
        "on-secondary-container": "#4d5d7e",
        "surface-dim": "#d8dadb",
        "primary-container": "#004a99",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-background": "#191c1d",
        "surface-container": "#eceeef",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
};
