/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        auth: {
          "on-secondary": "#520070",
          "inverse-primary": "#00677f",
          "on-primary-container": "#00566a",
          "primary-container": "#00d2ff",
          background: "#111225",
          "outline-variant": "#3c494e",
          "secondary-container": "#6e208c",
          tertiary: "#dad9ff",
          "tertiary-fixed-dim": "#c0c1ff",
          primary: "#a5e7ff",
          "surface-container-high": "#27283d",
          "surface-container-low": "#191a2d",
          "on-error": "#690005",
          "tertiary-container": "#b9bbff",
          "on-surface": "#e1e0fb",
          "surface-container-highest": "#323348",
          "primary-fixed": "#b6ebff",
          "error-container": "#93000a",
          "on-secondary-container": "#e498ff",
          "on-background": "#e1e0fb",
          surface: "#111225",
          "surface-dim": "#111225",
          "primary-fixed-dim": "#47d6ff",
          "inverse-surface": "#e1e0fb",
          secondary: "#edb1ff",
          "surface-container-lowest": "#0b0c1f",
          "on-tertiary-container": "#3f43a3",
          "surface-variant": "#323348",
          "surface-bright": "#37374d",
          "surface-container": "#1d1e32",
          "on-primary-fixed-variant": "#004e60",
          "secondary-fixed-dim": "#edb1ff",
          "on-tertiary-fixed": "#04006d",
          "tertiary-fixed": "#e1e0ff",
          "on-primary-fixed": "#001f28",
          "on-surface-variant": "#bbc9cf",
          "surface-tint": "#47d6ff",
          error: "#ffb4ab",
          "on-secondary-fixed": "#320046",
          "on-tertiary-fixed-variant": "#373a9b",
          "on-error-container": "#ffdad6",
          "on-secondary-fixed-variant": "#6e208c",
          "secondary-fixed": "#f9d8ff",
          "inverse-on-surface": "#2e2f43",
          outline: "#859399",
          "on-tertiary": "#1e2084",
          "on-primary": "#003543",
        },
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1d",
        "primary-fixed": "#d7e2ff",
        "on-secondary-fixed": "#081b38",
        "on-primary-container": "#9bbdff",
        "outline-variant": "#c2c6d3",
        secondary: "#4e5f7f",
        "on-secondary-fixed-variant": "#364766",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb694",
        "surface-container-low": "#f2f4f5",
        "surface-container-high": "#e6e8e9",
        primary: "#00346f",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#b6c7ec",
        "on-surface-variant": "#424751",
        "surface-container-highest": "#e1e3e4",
        "on-primary-fixed-variant": "#00458f",
        outline: "#737783",
        "tertiary-container": "#833301",
        "on-primary-fixed": "#001b3f",
        "on-secondary": "#ffffff",
        tertiary: "#5f2200",
        "surface-bright": "#f8fafb",
        "tertiary-fixed": "#ffdbcc",
        "inverse-on-surface": "#eff1f2",
        "inverse-surface": "#2e3132",
        "primary-fixed-dim": "#abc7ff",
        background: "#f8fafb",
        "inverse-primary": "#abc7ff",
        "secondary-container": "#c6d7fd",
        "surface-variant": "#e1e3e4",
        "on-tertiary-container": "#ffa77e",
        "on-tertiary-fixed": "#351000",
        surface: "#f8fafb",
        "on-error": "#ffffff",
        "secondary-fixed": "#d7e2ff",
        error: "#ba1a1a",
        "surface-tint": "#255dad",
        "on-secondary-container": "#4d5d7e",
        "surface-dim": "#d8dadb",
        "primary-container": "#004a99",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-background": "#191c1d",
        "surface-container": "#eceeef",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        "auth-display": ["Plus Jakarta Sans", "Manrope", "sans-serif"],
        "auth-headline": ["Plus Jakarta Sans", "Manrope", "sans-serif"],
        "auth-title": ["Plus Jakarta Sans", "Manrope", "sans-serif"],
        "auth-body": ["Hanken Grotesk", "Inter", "sans-serif"],
        "auth-label": ["Hanken Grotesk", "Inter", "sans-serif"],
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
      },
      fontSize: {
        "auth-display-lg": ["48px", { lineHeight: "56px", letterSpacing: "0", fontWeight: "700" }],
        "auth-body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "auth-headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "auth-title-md": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "auth-headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "auth-body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "auth-label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
